services:
  postgresql:
    image: postgres:latest-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: validatable
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
