name: Test
on:
  push:
    branches:
      - main
    paths:
      - "validatable/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install
        run: |
          make install-linting
          pip freeze
      - name: lint
        run: make lint
